### PR TITLE
Update 12.12.1

### PR DESCRIPTION
**Pull request by pyt-viper**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

I updated the PyTrilinos build to include all of the same packages in the Trilinos build (except for PyTrilinos) so that the configurations will match.

### CODE REVIEW

**Comment by pyt-viper** [comment]
@isuruf my `meta.yaml` has

```
build:
  number: 0
  skip: True  # [ osx or win or py3k ]
```

but the Linux version does not build and the MacOS-X version does.  What am I doing wrong?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

File: recipe/meta.yaml [hunk 1]
```diff
@@ -1,22 +1,21 @@
...
 
 package:
   name: {{ name|lower }}
   version: {{ version }}
 
 source:
-  fn: trilinos-{{ version }}-Source.tar.gz
-  url: http://trilinos.csbsju.edu/download/files/trilinos-{{ version }}-Source.tar.gz
+  fn: trilinos-release-{{ dashversion }}.tar.gz
+  url: http://github.com/trilinos/Trilinos/archive/trilinos-release-{{ dashversion }}.tar.gz
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
  url: http://github.com/trilinos/Trilinos/archive/trilinos-release-{{ version | replace('.', '-') }}.tar.gz
```

File: recipe/meta.yaml [hunk 2]
```diff
@@ -1,22 +1,21 @@
 {% set name = "PyTrilinos" %}
-{% set version = "12.10.1" %}
-{% set sha256 = "ea8ff573bb1f452f2585950cdabe7e2c84cb35013844c58dc878c66bd4245e06" %}
+{% set version = "12.12.1" %}
+{% set dashversion = "12-12-1" %}
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
```

File: recipe/meta.yaml [hunk 3]
```diff
@@ -1,22 +1,21 @@
...
+{% set sha256 = "5474c5329c6309224a7e1726cf6f0d855025b2042959e4e2be2748bd6bb49e18" %}
 {% set mpi = 'mpich 3.2.*' %}
```
Comment (hmaarrfk) [inline recipe/meta.yaml]: This pinning is probably harsh and pad.
```suggestion
```

Comment (hmaarrfk) [reply recipe/meta.yaml]: It seems you aren't even usiing it anyway.

File: recipe/meta.yaml [hunk 4]
```diff
@@ -1,22 +1,21 @@
 {% set name = "PyTrilinos" %}
-{% set version = "12.10.1" %}
-{% set sha256 = "ea8ff573bb1f452f2585950cdabe7e2c84cb35013844c58dc878c66bd4245e06" %}
+{% set version = "12.12.1" %}
+{% set dashversion = "12-12-1" %}
+{% set sha256 = "5474c5329c6309224a7e1726cf6f0d855025b2042959e4e2be2748bd6bb49e18" %}
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
```
Probably easier to just not have this up here.

File: recipe/meta.yaml [hunk 5]
```diff
@@ -1,22 +1,21 @@
...
 {% set mpi = 'mpich 3.2.*' %}
 
 package:
   name: {{ name|lower }}
   version: {{ version }}
 
 source:
-  fn: trilinos-{{ version }}-Source.tar.gz
-  url: http://trilinos.csbsju.edu/download/files/trilinos-{{ version }}-Source.tar.gz
+  fn: trilinos-release-{{ dashversion }}.tar.gz
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
```
not really needed

File: recipe/meta.yaml [hunk 6]
```diff
@@ -1,22 +1,21 @@
...
+  url: http://github.com/trilinos/Trilinos/archive/trilinos-release-{{ dashversion }}.tar.gz
   sha256: {{ sha256 }}
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
  sha256: 5474c5329c6309224a7e1726cf6f0d855025b2042959e4e2be2748bd6bb49e18
```

**Comment by hmaarrfk** [comment]
I think that this package should now be compatible with python 3

File: recipe/meta.yaml [hunk 7]
```diff
@@ -1,22 +1,21 @@
...
-  patches:
-    - 12.10-fixes.patch
 
 build:
-  number: 2
-  skip: true  # [win or py3k]
+  number: 0
+  skip: True  # [ osx or win or py3k ]
```
Comment (hmaarrfk) [inline recipe/meta.yaml]:
```suggestion
  skip: True  # [ osx or win]
```

It seems 12.12 is now compatible with python 3

File: recipe/meta.yaml [hunk 8]
```diff
@@ -25,15 +24,16 @@ requirements:
...
   host:
-    - {{ mpi }}
+    - mpi
     - python
-    - swig 3.0.10
+    - swig 3.0.11
     - doxygen
     - numpy
     - mpi4py
+    - trilinos {{ version }}
```
Comment (hmaarrfk) [inline recipe/meta.yaml]: Are you sure you are using the prebuilt trilinos package? Compilation seems to be taking a while.

Comment (pyt-viper) [reply recipe/meta.yaml]: Thanks for all the help.  The PyTrilinos and Trilinos feedstocks haven't been updated in several months, and there is plenty of bit rot to address.  Some of what you have attempted to fix was just me trying to isolate issues, but that's fine.

Unfortunately, there isn't a way to build PyTrilinos using an installed version of Trilinos.  My discussions with conda-forge developers led me to believe that things would still work.

Comment (hmaarrfk) [reply recipe/meta.yaml]: so do you need to depend on this package at all? will you be creating a conflict between packages?

Comment (pyt-viper) [reply recipe/meta.yaml]: We'll see.  This is the first time I am trying it.

Actually, I have been seeing a compilation error that might be due to a conflict between the Trilinos and PyTrilinos feedstocks ... it's been bugging me, but if the PyTrilinos build system is pulling in the installed Trilinos header (and configuration) files, then it would explain the compilation error.

Perhaps I need to set up Trilinos and PyTrilinos to be mutually exclusive.  You can install one but not both.  If you install PyTrilinos, it will have everything Trilinos has, plus the python wrappers.  Can we do that?

Comment (hmaarrfk) [reply recipe/meta.yaml]: I kinda did that for opencv.

You have one package install everything. But the other add in the python dependencies.

It will polute the environment with a few  `site-packages` directories, for those that do not want python, but it avoids conflicts. First lets try to get the package to compile. You got really close!
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=107389&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=4646

Comment (pyt-viper) [reply recipe/meta.yaml]: Yes, it did get close.  And on Linux, we do not see the compilation error I was referencing.

How do you propose we proceed?  If it was just me, I might try reproducing the "no constructor" error locally using docker, although while I have installed docker locally, I haven't really ever used it.

I'm pretty sure we could disable almost all the Trilinos packages except Teuchos and still reproduce the error.  This would save a lot of time.

Comment (hmaarrfk) [reply recipe/meta.yaml]: I would apply a few of the cleanups i recommended, and stop skipping python3 or osx. 12.18.1 is causing me griefs.

Comment (pyt-viper) [reply recipe/meta.yaml]: OK.  I'll apply your cleanups.  I was skipping stuff to isolate problems.

The reason I was working with 12.12.1 was to see if I could set up the dependencies issue properly without the headache of newer versions.

I have gotten the current version of Trilinos/PyTrilinos to compile locally under an Anaconda environment to supply python, numpy, swig, etc.  I forget if there is a 12.18.1 tarball, but if there is, my changes have probably not made it into it yet.

Comment (hmaarrfk) [reply recipe/meta.yaml]: Yeah, i've been trying to patchup 12.18.1 with what seems to be yoru changes. Either will work.

Comment (pyt-viper) [reply recipe/meta.yaml]: Are you trying to create a 12.18.1 feedstock, or just get PyTrilinos to compile locally under Trilinos 12.18.1?

Comment (hmaarrfk) [reply recipe/meta.yaml]: See my effort here: https://github.com/conda-forge/pytrilinos-feedstock/pull/22

File: recipe/meta.yaml [hunk 9]
```diff
@@ -25,15 +20,16 @@ requirements:
...
 
   run:
-    - {{ mpi }}
+    - mpi
```
Comment (hmaarrfk) [inline recipe/meta.yaml]: Should this be `mpich`???

Comment (pyt-viper) [reply recipe/meta.yaml]: I would like it to support mpich or openmpi.

Comment (hmaarrfk) [reply recipe/meta.yaml]: Do you need to copy the structure of https://github.com/conda-forge/trilinos-feedstock/tree/master/recipe
or is that recipe too old?

Comment (hmaarrfk) [reply recipe/meta.yaml]: https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=mpi#building-mpi-variants

It seems like you do.

Comment (pyt-viper) [reply recipe/meta.yaml]: My thinking is, that if there are not going to be conflicts, the PyTrilinos structure needs to be as close to the Trilinos structure as possible.  Your linked Trilinos feedstock shouldn't be too old for 12.12.1.

Comment (hmaarrfk) [reply recipe/meta.yaml]: I thought we were:
1. Going to remvoe the trilinos dependency
2. Rebuild the trilinos packages from scratch. <- this is happening anyway.

Comment (pyt-viper) [reply recipe/meta.yaml]: There are a lot of balls in the air.  Since the Linux build made it to testing without the compilation error I had seen on MacOS, I left the trilinos dependency in there.  I'm willing to remove it, though.

File: recipe/build.sh [hunk 10]
```diff
@@ -26,22 +26,53 @@ cmake \
...
+  -D Trilinos_ENABLE_MueLu:BOOL=ON \
+  -D Trilinos_ENABLE_Rythmos:BOOL=ON \
+  -D Trilinos_ENABLE_Stokhos:BOOL=ON \
+  -D Trilinos_ENABLE_ROL:BOOL=ON \
+  -D Trilinos_ENABLE_Piro:BOOL=ON \
+  -D Trilinos_ENABLE_TrilinosCouplings:BOOL=ON \
+  -D Trilinos_ENABLE_Pike:BOOL=ON \
   -D Trilinos_ENABLE_PyTrilinos:BOOL=ON \
   -D PyTrilinos_ENABLE_TESTS:BOOL=ON \
   -D PyTrilinos_ENABLE_EXAMPLES:BOOL=ON \
```
Comment (hmaarrfk) [inline recipe/build.sh]: can we skip the ctest command? I have a feeling that things might have worked, but some test dependency is missing.

File: recipe/meta.yaml (hunk 9 above)
Comment (hmaarrfk) [reply recipe/meta.yaml]: It seems to me like you would be clobbering things. that isn't good.

**Comment by pyt-viper** [comment]
Build failure summary, 1/2/20, 4:00pm ET:

- OSX, Py2.7: same build failure I was seeing before, that I now believe is due to dependency on trilinos conda-forge package.  Will remove dependency

- Linux, Py2.7: build succeeds (may be picking up configuration from downloaded tarball, not installed trilinos), but attempts to `import` PyTrilinos packages fail due to multiple `AttributeError: No constructor defined` errors.  We can disable the `ctest`, but I think the `import` statements will still fail.

- OS X, Linux, Py3.x: These appear to all be failing because of a couple scripts that are used in the `cmake` configuration phase.  In the `github.com/trilinos/Trilinos` repository, in the `trilinos-release-12-12-1` branch, these scripts have been upgraded for use with both Python 2 and 3.  But in the tarball downloaded for the feedstocks, these changes are not included.  The best approach is probably a patch.

**Comment by hmaarrfk** [comment]
If you can isolate the patches, you can add a `.patch` at the end of a commit url or PR url to get the patch.

**Comment by hmaarrfk** [comment]
Well now you are getting the same errors I was with `12.18`
```
  Error converting Teuchos C++ Doxygen comments to Python docstrings:
```

**Comment by hmaarrfk** [comment]
So strange.

**Comment by pyt-viper** [comment]
I think what is happening is that the patch file I created is not getting applied properly.

In the Trilinos GitHub repository, there is a branch called trilinos-release-12-12-1-branch.  I think the tarball is based on commit `89b8c7`, which is upstream of the head.

@hmaarrfk Do you know the correct procedure for creating a proper patch file in this situation?

**Comment by hmaarrfk** [comment]
1. Clone the repo locally. 
2. Checkout the 12.12-1 tag
3. Cherry-pick the commit you need.
4. fixup the patch
5. commit locally.
6. `git diff -u HEAD 12.12-1-or-whatever-the-tag-is > my_patch.patch`

**Comment by hmaarrfk** [comment]
you might need to create a branch between 2 and 3

**Comment by pyt-viper** [comment]
I have replicated the "No constructor defined" error using Python 2, and I am seeing memory leaks using Python 3.  There are a couple issues to work out before getting 12.12.1 to work.

**Comment by hmaarrfk** [comment]
> I have replicated the "No constructor defined" error using Python 2

Thats a start! You'll find it eventually!

>  I am seeing memory leaks using Python 3

This is for upstream to fix, not us.

**Comment by pyt-viper** [comment]
Well, *I* am the new “upstream” for the PyTrilinos package under Trilinos...

You are suggesting that we ignore these issues in our attempt to get the conda-forge installers working.  I appreciate that.  But I don’t think we can:

* The “No constructor defined” error will prevent `import` of the PyTrilinos modules,
* The memory leak causes a ton of warnings to be printed after a PyTrilinos script runs, obscuring output and being a general nuisance.

I checked the `develop` branch of Trilinos with PyTrilinos enabled, and both of these issues are fixed, for Python 2 *and* 3.  I just need to find the commits.

**Comment by hmaarrfk** [comment]
So maybe start with 12-18 instead of 12-18 

Typically I can find it easy to patch this on the latest release, two releases away is hard.

**Comment by pyt-viper** [comment]
Makes sense...
